- Jenkinsfile
> Add pagefind indexing

- config.toml
- content/services/aarch64_request_hosting.md
- Disable paths to lowercase
- Fix aarch64 hosting url
> Fix URL differences between old and new site

- data/powerdev_open_source_projects.yml
- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=33652
> Add OpenSSL to openpower

- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=33671
https://divestos.org/pages/news#end
> Remove DivestOS

- content/services/aarch64_request_hosting.md
- content/services/ibm_z_request_ci.md
- content/services/openpower_gpu_request.md
- content/services/power_ci_request_hosting.md
- content/services/power_request_hosting.md
- content/services/request_hosting.md
- themes/osuosl/static/js/formsender-error.js
> Add missing formsender-error.js and fix paths

- config.toml
- content/services/aarch64_request_hosting.md
- content/services/ibm_z_request_ci.md
- content/services/openpower_gpu_request.md
- content/services/power_ci_request_hosting.md
- content/services/power_request_hosting.md
- content/services/request_hosting.md
> Update token and other misc fixes

- content/services/opence.md
Added Open-CE 1.11.5 and updated a bunch of wording and other versions not pulled in sync from pelican -> hugo.
> Add v1.11.5

- content/services/opence.md
Making it more clear that P10 stands/operates and builds are separate from Nvidia GPUs.
> Open-CE - update wording to reflect platform options

- content/services/opence.md
- v1.11.4
- CUDA 11.8 dropped
- Python 3.10 dropped
> Add update regarding soft-component support

- data/powerdev_open_source_projects.yml
- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=33707
> Add Debian Reproducible Builds

- content/blog/osl-future.md
> Add Future of OSL in Jeopardy post

- content/blog/osl-future.md
- content/donate/faq.md
> Fix link and add money breakdown

- content/donate/_index.md
> Update donate page with better wording

- themes/osuosl/layouts/index.html
Added a more visible donation button to the landing page in order to make it easily accessible.
> Created donation link in hero bar

- archetypes/blog.md
- content/blog/osl-future-update.md
- themes/osuosl/layouts/partials/footer.html
Also:
- Update copyright year
- Fix date format when creating new pages
> OSL Future Update blog post

- content/services/opence.md
> Add x86_64 completion to v1.11.6

- data/projects.yml
We are now providing VMs to the CPAN group.
[Support Ticket](https://support.osuosl.org/Ticket/Display.html?id=33910)
> Added VM to CPAN listing

- data/powerdev_open_source_projects.yml
- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=33889
> Adding LLVM BOLT information

- data/powerdev_open_source_projects.yml
- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=34087
> Adding Information regarding Linux Kernel development with a BPF memory model

- data/powerdev_open_source_projects.yml
- data/projects.yml
https://support.osuosl.org/Ticket/Display.html?id=34132
> Adding Information for liboqs
